INSERT INTO BRAND (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID) VALUES(nextval('hibernate_sequence'), 'BMW','BMW',1,1,CURRENT_DATE,1 );
INSERT INTO BRAND (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID) VALUES(nextval('hibernate_sequence'),'FIAT','FIAT',1,1,CURRENT_DATE,1 );

INSERT INTO CAR_MODEL (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,DAILY_COST,BRAND_ID) VALUES(nextval('hibernate_sequence'),'EGEA','FIAT_EGEA',1,1,CURRENT_DATE,1,100,(SELECT ID FROM BRAND WHERE CODE='FIAT') );
INSERT INTO CAR_MODEL (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,DAILY_COST,BRAND_ID) VALUES(nextval('hibernate_sequence'),'320D','BMW_320D',1,1,CURRENT_DATE,1,100,(SELECT ID FROM BRAND WHERE CODE='BMW') );

INSERT INTO CAR (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,MODEL_YEAR,COLOR,PLATE,MODEL_ID) VALUES(nextval('hibernate_sequence'), 'FIAT EGEA1','FIAT_EGEA1',1,1,CURRENT_DATE,1,2018,1,'06AS345',(SELECT ID FROM CAR_MODEL WHERE CODE='FIAT_EGEA') );
INSERT INTO CAR (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,MODEL_YEAR,COLOR,PLATE,MODEL_ID) VALUES(nextval('hibernate_sequence'), 'FIAT EGEA2','FIAT_EGEA2',1,1,CURRENT_DATE,1,2019,0,'06S3E5',(SELECT ID FROM CAR_MODEL WHERE CODE='FIAT_EGEA') );
INSERT INTO CAR (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,MODEL_YEAR,COLOR,PLATE,MODEL_ID) VALUES(nextval('hibernate_sequence'), 'BMW 320D_1','BMW_320D_1',1,1,CURRENT_DATE,1,2018,1,'34AD345',(SELECT ID FROM CAR_MODEL WHERE CODE='BMW_320D') );
INSERT INTO CAR (ID,NAME,CODE,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,MODEL_YEAR,COLOR,PLATE,MODEL_ID) VALUES(nextval('hibernate_sequence'), 'BMW 320D_2','BMW_320D_2',1,1,CURRENT_DATE,1,2018,1,'34ADD45',(SELECT ID FROM CAR_MODEL WHERE CODE='BMW_320D') );

INSERT INTO CUSTOMER (ID,FIRST_NAME, LAST_NAME,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,SSN) VALUES(nextval('hibernate_sequence'), 'AHMET','DOGAN',1,1,CURRENT_DATE,1 ,1000);
INSERT INTO CUSTOMER (ID,FIRST_NAME, LAST_NAME,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,SSN) VALUES(nextval('hibernate_sequence'), 'MEHMET','DOGAN',1,1,CURRENT_DATE,1 ,1001);
INSERT INTO CUSTOMER (ID,FIRST_NAME, LAST_NAME,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,SSN) VALUES(nextval('hibernate_sequence'), 'ALI','CAN',1,1,CURRENT_DATE,1 ,1002);

INSERT INTO RENT (ID,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,BEGIN_DATE,END_DATE,CAR_ID,CUSTOMER_ID) VALUES(nextval('hibernate_sequence'), 1,1,CURRENT_DATE,1,CURRENT_DATE ,CURRENT_DATE +10,(SELECT ID FROM CAR WHERE CODE='FIAT_EGEA2'),(SELECT ID FROM CUSTOMER WHERE SSN=1000));
INSERT INTO RENT (ID,VERSION,ACTIVE,CREATE_TIME,CREATE_USER_ID,BEGIN_DATE,END_DATE,CAR_ID,CUSTOMER_ID) VALUES(nextval('hibernate_sequence'), 1,1,CURRENT_DATE,1,CURRENT_DATE ,CURRENT_DATE +10,(SELECT ID FROM CAR WHERE CODE='FIAT_EGEA1'),(SELECT ID FROM CUSTOMER WHERE SSN=1001));





